# Generated by Django 5.2.17 on 2026-08-25 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('on_leave', 'On Leave')], default='present', max_length=20)),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, help_text='Calculated from check-in and check-out times', max_digits=5)),
                ('late_minutes', models.IntegerField(default=0, help_text='Minutes late beyond scheduled start')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='Hours worked beyond standard workday', max_digits=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'db_table': 'attendances',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
