# Generated by Django 5.2.17 on 2026-08-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Standard Company Attendance Policy', max_length=150)),
                ('work_start_time', models.TimeField(default='09:00:00', help_text='Standard office start time')),
                ('work_end_time', models.TimeField(default='17:00:00', help_text='Standard office end time')),
                ('grace_period_minutes', models.IntegerField(default=15, help_text='Grace period before marked as late (minutes)')),
                ('standard_working_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='Standard required working hours per day', max_digits=4)),
                ('overtime_threshold_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='Working hours threshold after which overtime is counted', max_digits=4)),
                ('require_location', models.BooleanField(default=False, help_text='Require IP or location check-in')),
                ('notes', models.TextField(blank=True, default='Standard working policy applied across all branches.')),
            ],
            options={
                'db_table': 'attendance_policies',
            },
        ),
    ]
