# Generated by Django 5.2.17 on 2026-08-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hr_comment',
            field=models.TextField(blank=True, default='', help_text='HR remark — visible to the employee but only editable by HR/Admin'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='break_duration',
            field=models.IntegerField(default=60, help_text='Break duration in minutes'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('on_leave', 'On Leave'), ('early_leave', 'Early Leave'), ('incomplete', 'Incomplete')], default='present', max_length=20),
        ),
    ]
