# Generated by Django 5.2.17 on 2026-08-30 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recruitment_candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(upload_to='cv_uploads/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='recruitment.candidate')),
            ],
            options={
                'db_table': 'candidate_cvs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.PositiveIntegerField(help_text='Overall Match Score 0-100%')),
                ('recommendation', models.CharField(choices=[('Strong Match', 'Strong Match'), ('Moderate Match', 'Moderate Match'), ('Weak Match', 'Weak Match')], max_length=50)),
                ('experience_relevant_years', models.PositiveIntegerField(default=0)),
                ('experience_meets_requirement', models.BooleanField(default=False)),
                ('education_qualification', models.CharField(blank=True, default='', max_length=255)),
                ('education_meets_requirement', models.BooleanField(default=False)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('missing_requirements', models.JSONField(blank=True, default=list)),
                ('raw_json_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='recruitment.candidatecv')),
            ],
            options={
                'verbose_name': 'CV Analysis',
                'verbose_name_plural': 'CV Analyses',
                'db_table': 'cv_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Job responsibilities and overview')),
                ('required_skills', models.TextField(help_text='Comma-separated or bullet list of required skills')),
                ('preferred_skills', models.TextField(blank=True, default='', help_text='Preferred or bonus skills')),
                ('required_experience_years', models.PositiveIntegerField(default=0, help_text='Minimum years of experience required')),
                ('educational_requirements', models.TextField(blank=True, default='', help_text='Minimum education or degree requirements')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vacancies', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='organization.department')),
            ],
            options={
                'verbose_name': 'Job Vacancy',
                'verbose_name_plural': 'Job Vacancies',
                'db_table': 'job_vacancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidatecv',
            name='job_vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_cvs', to='recruitment.jobvacancy'),
        ),
        migrations.CreateModel(
            name='MatchedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('Strong', 'Strong'), ('Moderate', 'Moderate'), ('Weak', 'Weak')], default='Moderate', max_length=50)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_skills', to='recruitment.cvanalysis')),
            ],
            options={
                'db_table': 'cv_matched_skills',
                'ordering': ['skill'],
            },
        ),
        migrations.CreateModel(
            name='MissingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=150)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_skills', to='recruitment.cvanalysis')),
            ],
            options={
                'db_table': 'cv_missing_skills',
                'ordering': ['skill'],
            },
        ),
    ]
